package com.famora.audit.entity;

public enum AuditAction {
    USER_REGISTERED, USER_LOGGED_IN, USER_LOGGED_OUT,
    FAMILY_CREATED, FAMILY_UPDATED, FAMILY_MEMBER_INVITED, FAMILY_MEMBER_JOINED, FAMILY_MEMBER_REMOVED, FAMILY_MEMBER_ROLE_UPDATED,
    VAULT_ITEM_CREATED, VAULT_ITEM_UPDATED, VAULT_ITEM_DELETED, VAULT_ITEM_VIEWED,
    NOTE_CREATED, NOTE_UPDATED, NOTE_DELETED,
    FINANCE_TRANSACTION_CREATED, FINANCE_TRANSACTION_UPDATED, FINANCE_TRANSACTION_DELETED
}
