package com.famora.audit.entity;

public enum AuditAction {
  USER_REGISTERED, USER_LOGGED_IN, USER_LOGGED_OUT,
  FAMILY_CREATED, FAMILY_UPDATED, FAMILY_MEMBER_INVITED, FAMILY_MEMBER_JOINED, FAMILY_MEMBER_REMOVED, FAMILY_MEMBER_ROLE_UPDATED,
  VAULT_ITEM_CREATED, VAULT_ITEM_UPDATED, VAULT_ITEM_DELETED, VAULT_ITEM_VIEWED,
  NOTE_CREATED, NOTE_UPDATED, NOTE_DELETED,
  FINANCE_TRANSACTION_CREATED, FINANCE_TRANSACTION_UPDATED, FINANCE_TRANSACTION_DELETED,
  DOCUMENT_CREATED, DOCUMENT_UPDATED, DOCUMENT_DELETED, DOCUMENT_VIEWED, DOCUMENT_DOWNLOADED,
  FILE_CREATED, FILE_UPDATED, FILE_DELETED, FILE_VIEWED, FILE_DOWNLOADED,
  EMERGENCY_CONTACT_CREATED, EMERGENCY_CONTACT_UPDATED, EMERGENCY_CONTACT_DELETED,
  BUSINESS_PRODUCT_CREATED, BUSINESS_PRODUCT_UPDATED, BUSINESS_PRODUCT_DELETED,
  BUSINESS_EXPENSE_CREATED, BUSINESS_EXPENSE_UPDATED, BUSINESS_EXPENSE_DELETED,
  BUSINESS_INVITATION_CREATED, BUSINESS_INVITATION_CANCELLED, BUSINESS_INVITATION_ACCEPTED,
  BUSINESS_MEMBER_ROLE_UPDATED, BUSINESS_MEMBER_REMOVED,
  BUSINESS_DAILY_REPORT_CREATED, BUSINESS_DAILY_REPORT_SUBMITTED,
  BUSINESS_DAILY_REPORT_REVISION_SUBMITTED, BUSINESS_DAILY_REPORT_REVISION_REQUESTED,
  BUSINESS_DAILY_REPORT_APPROVED, BUSINESS_DAILY_REPORT_REJECTED, BUSINESS_DAILY_REPORT_VOIDED,
}
