package com.famora.notification.enums;

public enum NotificationType {
  FAMILY_INVITATION_ACCEPTED,
  FAMILY_LEAVE_REQUESTED,
  FAMILY_LEAVE_APPROVED,
  FAMILY_LEAVE_REJECTED,
  FAMILY_OWNERSHIP_TRANSFERRED,
  BUSINESS_INVITATION_ACCEPTED,
  BUSINESS_DAILY_REPORT_SUBMITTED,
  BUSINESS_DAILY_REPORT_APPROVED,
  BUSINESS_DAILY_REPORT_REJECTED,
  BUSINESS_DAILY_REPORT_REVISION_REQUESTED,
  BACKUP_UPLOAD_COMPLETED,
  BACKUP_UPLOAD_FAILED,
  DOCUMENT_EXPIRING_SOON,
  TRACKER_DUE_SOON,
  DEBT_DUE_SOON
}
