package com.famora.tracker.enums;

public enum TrackerType {
  CUSTOM,
  HABIT,
  REMINDER,
  DOCUMENT_EXPIRY,
  BILL_PAYMENT,
  HEALTH_ROUTINE,
  MEDICINE_SUPPLEMENT,
  HEALTH_APPOINTMENT,
  CHILD_LEARNING_ACTIVITY,
  BUSINESS_DAILY_REPORT
}
