UPDATE famora.documents
SET document_type = CASE document_type
    WHEN 'ID_CARD' THEN 'KTP'
    WHEN 'MARRIAGE_CERTIFICATE' THEN 'MARRIAGE_BOOK'
    WHEN 'INSURANCE' THEN 'INSURANCE_POLICY'
    WHEN 'MEDICAL' THEN 'MEDICAL_CHECKUP_RESULT'
    WHEN 'SCHOOL' THEN 'DIPLOMA'
    WHEN 'TAX' THEN 'NPWP'
    WHEN 'VEHICLE' THEN 'STNK'
    WHEN 'PROPERTY' THEN 'HOUSE_CERTIFICATE'
    WHEN 'BUSINESS' THEN 'EMPLOYMENT_CONTRACT'
    WHEN 'OTHER' THEN 'OTHER_DOCUMENT'
    ELSE document_type
END
WHERE document_type IN (
    'ID_CARD',
    'MARRIAGE_CERTIFICATE',
    'INSURANCE',
    'MEDICAL',
    'SCHOOL',
    'TAX',
    'VEHICLE',
    'PROPERTY',
    'BUSINESS',
    'OTHER'
);
